### PR TITLE
Fix: renamed default config file

### LINKED ISSUE #725: Refactor default bot config from `json` to `ts`
Original [comment](https://github.com/ubiquity/ubiquibot/pull/670#discussion_r1306600068)

There is the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json). 

We want to able to add comments to the default bot config. We can't transform the config from `json` to `yml` or `jsonc` because it requires using `fs.readFile()` which causes issues on production netlify build.

What should be done:
- refactor the [default bot config](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json) from `json` to a plain `ts` file

### PR DESCRIPTION
**Pull request by Wholesomebruh**
Resolves #725 

Quality Assurance: Passing checks

### CODE REVIEW

**Comment by Wholesomebruh** [comment]
@pavlovcik @rndquu , last PR was automatically closed as GitHub suggested to remove the commit and then resolve the conflicts. No extra changes are made. Please have a look at this.

**Comment by pavlovcik** [comment]
"QA" needs evidence like links

File: ubiquibot-config-default.ts [hunk 1]
```diff
@@ -90,5 +91,8 @@
   "enable-access-control": {
     "label": false,
     "organization": true
-  }
+  },
+  "stale-bounty-time":""
```
Comment (pavlovcik) [inline ubiquibot-config-default.ts:95]: This doesn't look right. Why did you remove "0d"

File: src/utils/private.ts [hunk 2]
```diff
@@ -4,7 +4,7 @@ import { MergedConfig, Payload } from "../types";
 import { Context } from "probot";
 import merge from "lodash/merge";
 
-import DEFAULT_CONFIG_JSON from "../../ubiquibot-config-default.json";
+import defaultConfig from "../../ubiquibot-config-default";
```
Comment (pavlovcik) [inline src/utils/private.ts:7]: This should still be a const so it should still be capitalized. You can set the object as readonly or as const to enforce that.

File: ubiquibot-config-default.ts (hunk 1 above)
Comment (Wholesomebruh) [reply ubiquibot-config-default.ts:95]: 0d wasn't [there](https://github.com/ubiquity/ubiquibot/blob/development/ubiquibot-config-default.json#L92) originally, thanks for mentioning. I will update it.

File: src/utils/private.ts (hunk 2 above)
Comment (Wholesomebruh) [reply src/utils/private.ts:7]: Got it, any more suggestions?

Comment (Wholesomebruh) [reply src/utils/private.ts]: Should be all caps or "DefaultConfig" ?

**Comment by Wholesomebruh** [comment]
@rndquu , any more suggestions or changes from your side on this?

File: src/utils/private.ts (hunk 2 above)
Comment (pavlovcik) [reply src/utils/private.ts]: `DEFAULT_CONFIG` to represent a const

File: ubiquibot-config-default.ts [hunk 3]
```diff
@@ -90,5 +91,8 @@
   "enable-access-control": {
     "label": false,
     "organization": true
-  }
+  },
+  "stale-bounty-time":"0d"
 }
+
+export default DefaultConfig;
```
Comment (pavlovcik) [inline ubiquibot-config-default.ts:98]:
```suggestion
export default DefaultConfig as readonly;
```

I'm not sure which way is correct but you can do `as readonly` or `as const` I'm pretty sure which will actually make this whole object immutable.

**Review by pavlovcik — CHANGES_REQUESTED** [review]

File: ubiquibot-config-default.ts (hunk 3 above)
Comment (Wholesomebruh) [reply ubiquibot-config-default.ts:98]: Got it, it will be 
```bash
export default DefaultConfig as const
```
Is "DefaultConfig" fine or it should be changed to "DEFAULT_CONFIG"?

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]
1/ If we change `json` to `ts` and need to read the config file in pay.ubq.fi, we should publish the repository to the npm registry, add it in package.json in pay.ubq.fi and import it.

2/ Then we should move ubiquibot-config-default.ts into the src folder to make sure it's being built/checked @Wholesomebruh

File: ubiquibot-config-default.ts (hunk 3 above)
Comment (0xcodercrane) [reply ubiquibot-config-default.ts:98]: DefaultConfig is fine to me

**Comment by 0xcodercrane** [comment]
The PR merge should be happening with the relevant changes in pay.ubq.fi right? @rndquu

**Comment by rndquu** [comment]
> The PR merge should be happening with the relevant changes in pay.ubq.fi right? @rndquu

You're free to merge the current PR

There is already a related [issue](https://github.com/ubiquity/pay.ubq.fi/issues/135) for onboarding refactoring

We will deploy a new version of pay.ubq.fi only when https://github.com/ubiquity/pay.ubq.fi/issues/135 is implemented so that nothing is broken

**Comment by 0xcodercrane** [comment]
Ok let me handle the merge once the conversations resolved.

File: ubiquibot-config-default.ts (hunk 3 above)
Comment (Wholesomebruh) [reply ubiquibot-config-default.ts]: None of them are working.
On adding "as readonly" it's giving "Type expected" error and 
On adding "as const" , it's showing "const" can be added to string, number, boolean,enum, array and object literals only.
 
Is "DefaultConfig" fine or it should be changed to "DEFAULT_CONFIG"?
@0xcodercrane mentioned "DefaultConfig" is fine and @pavlovcik asked to use "DEFAULT_CONFIG"

Comment (0xcodercrane) [reply ubiquibot-config-default.ts]: ok. I couldn't find @pavlovcik 's comment because it has been already resolved.

Lets go with `DEFAULT_CONFIG` and use const.

Comment (pavlovcik) [reply ubiquibot-config-default.ts]: Use chatgpt to figure out how to make objects immutable @Wholesomebruh

**Review by 0xcodercrane — APPROVED** [review]

**Review by 0xcodercrane — APPROVED** [review]

**Comment by 0xcodercrane** [comment]
@Wholesomebruh  bump for the second request: 
> 2/ Then we should move ubiquibot-config-default.ts into the src folder to make sure it's being built/checked

**Comment by Wholesomebruh** [comment]
@0xcodercrane , moved the ubiquity-config-default to src folder.

**Comment by pavlovcik** [comment]
> @0xcodercrane , moved the ubiquity-config-default to src folder.

This can break other systems, including the partner onboarding @rndquu rfc

**Comment by 0xcodercrane** [comment]
> > @0xcodercrane , moved the ubiquity-config-default to src folder.
> 
> This can break other systems, including the partner onboarding @rndquu is this all clear?

I don't think so

**Comment by rndquu** [comment]
> > > @0xcodercrane , moved the ubiquity-config-default to src folder.
> > 
> > 
> > This can break other systems, including the partner onboarding @rndquu is this all clear?
> 
> I don't think so

It does break the onboarding but we already have a related [issue](https://github.com/ubiquity/pay.ubq.fi/issues/135) for onboarding refactoring so we won't deploy a new version of pay.ubq.fi unless the https://github.com/ubiquity/pay.ubq.fi/issues/135 is implemented

**Comment by 0xcodercrane** [comment]
From my understanding of my questions before merging the PR, I was free to merge right? 

Ideally, we shouldn't merge the pr if it breaks something even if it is partner onboarding.

So I guess the solution here is to wrap up the related issues as soon as possible.

**Comment by rndquu** [comment]
> From my understanding of my questions before merging the PR, I was free to merge right?

yes

> So I guess the solution here is to wrap up the related issues as soon as possible

yes
