### PR TITLE
fix(config): add error for empty private key

### LINKED ISSUE #523: Add empty private key error
Right now if the `private-key-encrypted` param in the bot's config is not set then the bot shows this [error](https://github.com/ubiquibot/production/issues/25#issuecomment-1636710420) which is really misleading.

It happens because [here](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L78) the `autoPayMode` is set to `false` if there is no private key hence the error `Permit generation skipped since autoPayMode is disabled`. The error text should be similar to `Permit generation skipped because wallet private key is not set`.

What should be done:
1. Remove this [check](https://github.com/ubiquity/ubiquibot/blob/development/src/bindings/config.ts#L77)
2. [Here](https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/payout/action.ts) add an additional check for an empty private key which shows an appropriate error message in case the private key is not set.

### PR DESCRIPTION
**Pull request by Sadaf-A**
- Added a suitable error message when the private key is empty in loadConfig.

Resolves #523

### CODE REVIEW

File: src/bindings/config.ts [hunk 1]
```diff
@@ -85,7 +85,7 @@ export const loadConfig = async (context: Context): Promise<BotConfig> => {
   }
 
   if (botConfig.payout.privateKey == "") {
```
Comment (whilefoo) [inline src/bindings/config.ts:87]: This is not according to the specification of the issue. You need to remove this check here and add it in `src/handlers/payout/action.ts` just like the other checks

**Review by whilefoo — CHANGES_REQUESTED** [review]

File: src/bindings/config.ts (hunk 1 above)
Comment (Sadaf-A) [reply src/bindings/config.ts]: @whilefoo sorry about that, I have made the requested changes hope this will fix the issue!

**Review by whilefoo — CHANGES_REQUESTED** [review]
also please delete `package-lock.json` because we are using yarn

**Comment by Sadaf-A** [comment]
@whilefoo I have removed package-lock.json

**Review by whilefoo — DISMISSED** [review]

File: yarn.lock
Comment (pavlovcik) [inline yarn.lock:1]: It doesn't seem right to me that you changed the lock file without changing any other dependencies. Please undo this.

**Review by pavlovcik — CHANGES_REQUESTED** [review]

File: yarn.lock
Comment (Sadaf-A) [reply yarn.lock:1]: I'm sorry, I should've unstaged that before only I'll do it now.

**Comment by Sadaf-A** [comment]
@pavlovcik I have reverted the changes made to `yarn.lock` file as requested by you

**Comment by web4er** [comment]
> @pavlovcik I have reverted the changes made to `yarn.lock` file as requested by you

You should **Reolve Conversion** if you have made the requested change. 

Also, you need to resolve merge conflicts.

**Review by web4er — CHANGES_REQUESTED** [review]
- Fix your first comment to have the issue number in the same line as this:
 `Resolves #582`

- Also, [add a QA](https://github.com/ubiquity/ubiquibot#how-to-qa-any-additions-to-the-bot).

**Comment by pavlovcik** [comment]
@Draeieg can help with QA!

**Comment by Sadaf-A** [comment]
@pavlovcik Thanks, That would be great. I'm having a hard time making it.

**Comment by pavlovcik** [comment]
> @pavlovcik Thanks, That would be great. I'm having a hard time making it.

You just need to prove that your code works.

**Comment by Sadaf-A** [comment]
> > @pavlovcik Thanks, That would be great. I'm having a hard time making it.
> 
> You just need to prove that your code works.
> 
> I just reviewed the code. I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.

yes that would make more sense I'll try to implement it, I followed the instructions given in docs 
faced some issues maybe it's because it's my first time contributing here. However, I'll try to make a QA ASAP.

**Comment by whilefoo** [comment]
> I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.

It's already doing [that](https://github.com/ubiquity/ubiquibot/pull/582/files#diff-621e549acb4bd491fe5b9e9d07f1f7929daebe90f3fd13dbebe5368cf6988dbeR86) - returning the string which will be posted as a comment.

**Review by pavlovcik — APPROVED** [review]

**Comment by pavlovcik** [comment]
> > I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.
> 
> 
> 
> It's already doing [that](https://github.com/ubiquity/ubiquibot/pull/582/files#diff-621e549acb4bd491fe5b9e9d07f1f7929daebe90f3fd13dbebe5368cf6988dbeR86) - returning the string which will be posted as a comment. 
> 
> 

I approved based on this but I think it's worth waiting for good QA results as well.

**Review by pavlovcik — CHANGES_REQUESTED** [review]
Probably shouldnt be doing this test on this pull request. Try your development branch.

File: .github/ubiquibot-config.yml [hunk 2]
```diff
@@ -31,6 +31,7 @@ default-labels:
   - "Time: <1 Hour"
   - "Priority: 0 (Normal)"
 payment-permit-max-price: 1000
+private-key-encrypted: ""
```
Comment (web4er) [inline .github/ubiquibot-config.yml:34]: I think this is not needed here. `private-key-encrypted` is an org config. This file is repo config. This property is never read from repo config.

**Comment by Sadaf-A** [comment]
@pavlovcik I'm sorry I'll revert the changes.

**Review by web4er — CHANGES_REQUESTED** [review]

File: .github/ubiquibot-config.yml (hunk 2 above)
Comment (Sadaf-A) [reply .github/ubiquibot-config.yml:34]: So, How should i go about the QA

Comment (pavlovcik) [reply .github/ubiquibot-config.yml]: 1. Make an org 
2. Add your bot to your org
3. Don't add private key to config

Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: in the build step in `build.yml` SupaBase access key is required. So, I made a new project added the API key to the field it still gave error then I tried adding the jwt secret it stilll gave error. what should I enter in that field?

**Comment by Draeieg** [comment]
I'll QA as soon as all of the requested changes are implemented

File: .github/ubiquibot-config.yml (hunk 2 above)
Comment (web4er) [reply .github/ubiquibot-config.yml]: These docs are helpful https://github.com/ubiquity/ubiquibot/blob/development/supabase/README.md
What errors are you getting?

**Comment by Sadaf-A** [comment]
> > > I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.
> > 
> > 
> > 
> > It's already doing [that](https://github.com/ubiquity/ubiquibot/pull/582/files#diff-621e549acb4bd491fe5b9e9d07f1f7929daebe90f3fd13dbebe5368cf6988dbeR86) - returning the string which will be posted as a comment. 
> > 
> > 
> 
> I approved based on this but I think it's worth waiting for good QA results as well. 

@Draeieg Hey, hope you are doing well
I believe only the QA is left!

File: .github/ubiquibot-config.yml (hunk 2 above)
Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: I got an error which said the format of my key is wrong.
where should I find my the key
Is it the API key key or jwt token

Comment (web4er) [reply .github/ubiquibot-config.yml]: Look into readme file in PR https://github.com/ubiquity/ubiquibot/pull/607 , and adds info about **Payment Permits in a local instance**. It shows you how to generate a private key and use it. This will be helpful in fixing this issue and creating a QA. Please note there are two different kinds of private keys, one is used to encrypt another private key.

**Comment by Draeieg** [comment]
> > > > I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.
> > > 
> > > 
> > > It's already doing [that](https://github.com/ubiquity/ubiquibot/pull/582/files#diff-621e549acb4bd491fe5b9e9d07f1f7929daebe90f3fd13dbebe5368cf6988dbeR86) - returning the string which will be posted as a comment.
> > 
> > 
> > I approved based on this but I think it's worth waiting for good QA results as well.
> 
> @Draeieg Hey, hope you are doing well I believe only the QA is left!

image

I see 2 changes requested  and 1 conversation unresolved @web4er @pavlovcik

**Comment by Sadaf-A** [comment]
> > > > > I think the bot should leave a comment saying that the private key isn't set so that its clear to the end users, not just logging.
> > > > 
> > > > 
> > > > It's already doing [that](https://github.com/ubiquity/ubiquibot/pull/582/files#diff-621e549acb4bd491fe5b9e9d07f1f7929daebe90f3fd13dbebe5368cf6988dbeR86) - returning the string which will be posted as a comment.
> > > 
> > > 
> > > I approved based on this but I think it's worth waiting for good QA results as well.
> > 
> > @Draeieg Hey, hope you are doing well I believe only the QA is left!
> 
> image
> 
> I see 2 changes requested  and 1 conversation unresolved @web4er @pavlovcik 

Hi, It is related to the QA only.
I'll work on it today

File: .github/ubiquibot-config.yml (hunk 2 above)
Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: > These docs are helpful https://github.com/ubiquity/ubiquibot/blob/development/supabase/README.md What errors are you getting?

SUPABASE_KEY=XXX
The error said the format of my SUPABASE_KEY is incorrect where should I find the Key value? It could be that I put the wrong key in.

Comment (whilefoo) [reply .github/ubiquibot-config.yml]: This is the correct key

image

Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: It's working now but the format of `SUPABASE_ACCESS_TOKEN` seems to be wrong where may I find that?

Comment (whilefoo) [reply .github/ubiquibot-config.yml]: In case you haven't found it, it's [here](https://supabase.com/dashboard/account/tokens)

Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: now the bot is running but 
ubi
its giving the same message for every command

Comment (pavlovcik) [reply .github/ubiquibot-config.yml]: @wannacfuture do you know the solution?

Comment (wannacfuture) [reply .github/ubiquibot-config.yml]: @Sadaf-A 
Would you gimme the link, not screenshot?
Let me check it.

Comment (Sadaf-A) [reply .github/ubiquibot-config.yml]: > @Sadaf-A 
> Would you gimme the link, not screenshot?
> Let me check it.
> 
> And also you should check the config file if it has been set correctly like the file in ubiquibot staging repo(e.g.);

https://github.com/testing-ubiquibot1/ubiquibot/issues/1 here is the link
thanks for offering help!

**Comment by whilefoo** [comment]
QA: https://github.com/ubiquity-whilefoo/ubiquibot/issues/28 - it's working correctly

@Sadaf-A can you resolve conflicts?

@pavlovcik let's get this merged, it's been 3 weeks for this simple change

**Comment by Sadaf-A** [comment]
> QA: https://github.com/ubiquity-whilefoo/ubiquibot/issues/28 - it's working correctly
> 
> @Sadaf-A can you resolve conflicts?
> 
> @pavlovcik let's get this merged, it's been 3 weeks for this simple change

okay, I'll get onto it ASAP

**Comment by Sadaf-A** [comment]
> QA: [ubiquity-whilefoo#28](https://github.com/ubiquity-whilefoo/ubiquibot/issues/28) - it's working correctly
> 
> @Sadaf-A can you resolve conflicts?
> 
> @pavlovcik let's get this merged, it's been 3 weeks for this simple change

I have resolved the conflicts.

File: src/handlers/payout/action.ts [hunk 3]
```diff
@@ -90,7 +90,10 @@ export const handleIssueClosed = async () => {
     logger.info(`Penalty removed`);
     return;
   }
-
+  if (privateKey == "") {
```
Comment (pavlovcik) [inline src/handlers/payout/action.ts:93]: I guess this is acceptable because in our config loader, the default will be an empty string although I think it should be set to `null`

**Review by pavlovcik — APPROVED** [review]

File: src/handlers/payout/action.ts (hunk 3 above)
Comment (Sadaf-A) [reply src/handlers/payout/action.ts:93]: should i make the changes? And will it cancel auto merge?

Comment (pavlovcik) [reply src/handlers/payout/action.ts:93]: I made a new issue.

**Review by whilefoo — APPROVED** [review]

**Comment by pavlovcik** [comment]
Can somebody QA this?

**Comment by whilefoo** [comment]
QA: https://github.com/ubiquity-whilefoo/ubiquibot/issues/50

**Review by Draeieg — APPROVED** [review]

**Comment by pavlovcik** [comment]
@web4er please review again.

**Review by web4er — APPROVED** [review]
Working well.
QA
https://github.com/web4erOrg/ubiquibot/issues/77
https://github.com/web4erOrg/ubiquibot/issues/78
https://github.com/web4erOrg/ubiquibot/issues/79
https://github.com/web4erOrg/ubiquibot/issues/80

**Comment by Sadaf-A** [comment]
@whilefoo Hey, I had a doubt I set up my wallet and now this PR has been merged. So, should I expect to receive payment in that wallet and how long should it take?

**Comment by whilefoo** [comment]
@Sadaf-A you received the reward [here](https://github.com/ubiquity/ubiquibot/issues/523#issuecomment-1694405212)

**Comment by Sadaf-A** [comment]
> @Sadaf-A you received the reward [here](https://github.com/ubiquity/ubiquibot/issues/523#issuecomment-1694405212)

so i tried to recieve it i set up my metamask wallet and set the gnosis chain now it is saying i dont have enough tokens for the transaction. I'm also not able to get any xDai tokens the plus button is not clickable. what can i do?
