### PR TITLE
fix: derive weight automatically

### LINKED ISSUE #495: Refactor Config: Automatically Derive `weight` / ref
- Remove the `weight` property in the default config. 
- During runtime, when a bounty is being assistive priced by the bot, the bot should parse the number from the `Priority` label and use it in place of the `weight`
- Any words should be ignored from this parser, except for `Priority: ` of course, in order to understand that it is a priority label.
- Reference: https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228

### PR DESCRIPTION
**Pull request by byteballet**
Resolves #495

### CODE REVIEW

**Review by pavlovcik — CHANGES_REQUESTED** [review]
Priority weight was not implemented according to the spec:

> During runtime, when a bounty is being assistive priced by the bot, the bot should parse the number from the Priority label and use it in place of the weight

Did you accommodate the following?

> Any words should be ignored from this parser, except for Priority:  of course, in order to understand that it is a priority label.

---

- I'm reviewing the referenced comment https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228 and realized that I might not have been clear that I was only referring to `weight` in the context of the `Priority` label.

File: src/helpers/shared.ts [hunk 1]
```diff
@@ -19,3 +19,15 @@ export const shouldSkip = (): { skip: boolean; reason: string } => {
 };
 
 export const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
+
+export const calculateWeight = (label: LabelItem | undefined): number => {
+  if (!label) return 0;
+  const matches = label.name.match(/\d+/);
+  const number = matches && matches.length > 0 ? parseInt(matches[0]) : 0;
+  if (label.name.split(":")[0] === "Priority") return number + 1;
```
Comment (pavlovcik) [inline src/helpers/shared.ts:27]:
```suggestion
  if (label.name.split(":")[0] === "Priority") return number;
```

I think this might be correct for the spec.

File: src/helpers/shared.ts [hunk 2]
```diff
@@ -19,3 +19,15 @@ export const shouldSkip = (): { skip: boolean; reason: string } => {
...
+  if (label.name.includes("Hour")) return number * 0.125;
+  if (label.name.includes("Day")) return 1 + (number - 1) * 0.25;
+  if (label.name.includes("Week")) return number + 1;
+  if (label.name.includes("Month")) return 5 + (number - 1) * 8;
```
Comment (pavlovcik) [inline src/helpers/shared.ts:31]: Can you explain the math formulas?

**Comment by byteballet** [comment]
> Priority weight was not implemented according to the spec:
> 
> > During runtime, when a bounty is being assistive priced by the bot, the bot should parse the number from the Priority label and use it in place of the weight
> 
> Did you accommodate the following?
> 
> > Any words should be ignored from this parser, except for Priority:  of course, in order to understand that it is a priority label.
> 
> * I'm reviewing the referenced comment [feat: default config #383 (comment)](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228) and realized that I might not have been clear that I was only referring to `weight` in the context of the `Priority` label.
> * What is the `weight` representing for the `Time` labels? Does anybody know?
> * @wannacfuture is working on calculating the `Time` values in [`value` should be dynamically parsed from the time value using the `ms` library #431](https://github.com/ubiquity/ubiquibot/issues/431)



> Priority weight was not implemented according to the spec:
> 
> > During runtime, when a bounty is being assistive priced by the bot, the bot should parse the number from the Priority label and use it in place of the weight
> 
> Did you accommodate the following?
> 
> > Any words should be ignored from this parser, except for Priority:  of course, in order to understand that it is a priority label.
> 
> * I'm reviewing the referenced comment [feat: default config #383 (comment)](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228) and realized that I might not have been clear that I was only referring to `weight` in the context of the `Priority` label.
> * What is the `weight` representing for the `Time` labels? Does anybody know?
> * @wannacfuture is working on calculating the `Time` values in [`value` should be dynamically parsed from the time value using the `ms` library #431](https://github.com/ubiquity/ubiquibot/issues/431)

Bounty price is depend on both weight from priority and time label.
`const price = 1000 * base * timeValue * priority;`

File: src/helpers/shared.ts (hunk 2 above)
Comment (byteballet) [reply src/helpers/shared.ts:31]: I made the formulas to calculate weight from time-label name.
1Hour: 0.125
1Day: 1
1Week: 2
https://github.com/ubiquity/ubiquibot/blob/59825e4d7289a8da87bb3f568d9e69b183c821cf/ubiquibot-config-default.json#L16C8-L16C8

File: src/helpers/shared.ts [hunk 3]
```diff
@@ -19,3 +19,15 @@ export const shouldSkip = (): { skip: boolean; reason: string } => {
 };
 
 export const wait = (ms: number) => new Promise((r) => setTimeout(r, ms));
+
+export const calculateWeight = (label: LabelItem | undefined): number => {
+  if (!label) return 0;
+  const matches = label.name.match(/\d+/);
+  const number = matches && matches.length > 0 ? parseInt(matches[0]) : 0;
+  if (label.name.split(":")[0] === "Priority") return number;
```
Comment (whilefoo) [inline src/helpers/shared.ts:27]:
```suggestion
  if (label.name.toLowerCase().includes("priority")) return number;
```
Maybe it's more flexible to check if it includes the word `priority`

**Review by whilefoo — CHANGES_REQUESTED** [review]

**Comment by whilefoo** [comment]
https://github.com/ubiquity/ubiquibot/blob/f6e99dfb406559a044969bb82aff478daae172cd/src/handlers/shared/pricing.ts#L11C1-L11C1

@pavlovcik it appears we only use `weight` from priority and time labels to calculate the price. We only use the `value` to calculate end date.

File: src/helpers/shared.ts (hunk 3 above)
Comment (byteballet) [reply src/helpers/shared.ts]: I am not sure what I have to do with time label weight...
@pavlovcik rfc.

**Comment by pavlovcik** [comment]
> https://github.com/ubiquity/ubiquibot/blob/f6e99dfb406559a044969bb82aff478daae172cd/src/handlers/shared/pricing.ts#L11C1-L11C1
> 
> 
> 
> @pavlovcik it appears we only use `weight` from priority and time labels to calculate the price. We only use the `value` to calculate end date.

This looks like a mistake. One is to set the price, one is to get the price. Both should be using one or the other.

**Comment by byteballet** [comment]
> > https://github.com/ubiquity/ubiquibot/blob/f6e99dfb406559a044969bb82aff478daae172cd/src/handlers/shared/pricing.ts#L11C1-L11C1
> > @pavlovcik it appears we only use `weight` from priority and time labels to calculate the price. We only use the `value` to calculate end date.
> 
> This looks like a mistake. One function is to set the price, the other function is to get the price. Both should be using `value` or `weight`.

But now it seems weight and value are set default...

**Comment by whilefoo** [comment]
Both are using weight. The `timeValue` parameter in `calculateBountyPrice` is actually passed weight in https://github.com/ubiquity/ubiquibot/blob/f6e99dfb406559a044969bb82aff478daae172cd/src/helpers/label.ts#L74

**Comment by pavlovcik** [comment]
> Both are using weight

Then let's get rid of `value`

**Comment by byteballet** [comment]
> 
> Then let's get rid of `value`

`

> > Both are using weight
> 
> We should rename it to `value` and then fully get rid of `weight`

For both time and priority?

**Comment by byteballet** [comment]
> We should rename it to `value` and then fully get rid of `weight`

Please note that weight of both labels are used to calculate price and value in time label is used to calculate deadline.

**Comment by pavlovcik** [comment]
> > We should rename it to `value` and then fully get rid of `weight`
> 
> 
> 
> Please note that `weight` of both labels are used to calculate price and `value` in time label is used to calculate deadline. We can remove both `weight` and `value` and make a simple helper function that calculates them from label `name`. @pavlovcik 

Yes that is what the specification says. The only adjustment I have is to rename the property name from `weight` to `value`

**Comment by byteballet** [comment]
I removed both `value` and `weight` and made simple function that calculates them.

**Comment by pavlovcik** [comment]
@whilefoo you think you can re-review?

**Comment by byteballet** [comment]
> @whilefoo you think you can re-review?

Please note that I made a simple function that calculates value from time label name not using `ms` library to make clearer. It will conflict with https://github.com/ubiquity/ubiquibot/pull/638 . One of https://github.com/ubiquity/ubiquibot/pull/627 and https://github.com/ubiquity/ubiquibot/pull/638 might need modifications after another one is merged.

**Review by pavlovcik — APPROVED** [review]
This implementation looks pretty clean. Just needs QA.

File: src/helpers/shared.ts [hunk 4]
```diff
@@ -19,3 +19,27 @@ export const shouldSkip = (): { skip: boolean; reason: string } => {
...
+  const number = matches && matches.length > 0 ? parseInt(matches[0]) || 0 : 0;
+  if (label.name.toLowerCase().includes("priority")) return number;
+  if (label.name.toLowerCase().includes("hour")) return number * 0.125;
+  if (label.name.toLowerCase().includes("day")) return 1 + (number - 1) * 0.25;
+  if (label.name.toLowerCase().includes("week")) return number + 1;
+  if (label.name.toLowerCase().includes("month")) return 5 + (number - 1) * 8;
+  return 0;
+};
+
+export const calculateDuration = (label: LabelItem): number => {
```
Comment (whilefoo) [inline src/helpers/shared.ts:35]: duration calculation will be implemented in #638 so I'm not sure why did you also implement it

File: src/helpers/shared.ts [hunk 5]
```diff
@@ -19,3 +19,27 @@ export const shouldSkip = (): { skip: boolean; reason: string } => {
...
+
+export const calculateWeight = (label: LabelItem | undefined): number => {
+  if (!label) return 0;
+  const matches = label.name.match(/\d+/);
+  const number = matches && matches.length > 0 ? parseInt(matches[0]) || 0 : 0;
+  if (label.name.toLowerCase().includes("priority")) return number;
+  if (label.name.toLowerCase().includes("hour")) return number * 0.125;
+  if (label.name.toLowerCase().includes("day")) return 1 + (number - 1) * 0.25;
+  if (label.name.toLowerCase().includes("week")) return number + 1;
+  if (label.name.toLowerCase().includes("month")) return 5 + (number - 1) * 8;
```
Comment (whilefoo) [inline src/helpers/shared.ts:31]: I don't understand this calculation, how is weight related to time?

Comment (byteballet) [reply src/helpers/shared.ts:31]: I calculated it to adjust the value with the defaults.
1hour: 0.125
1day: 1
1 week: 2
2 weeks: 3
3 weeks: 4
1 month: 5
and made a rule for multiplier like 0.125, 0.25, 1, 8

File: src/helpers/shared.ts (hunk 4 above)
Comment (byteballet) [reply src/helpers/shared.ts:35]: Original spec is to remove both weight and value.

**Comment by Draeieg** [comment]
https://github.com/ubiquibot/staging/issues/144 tags haven't been changed in accordance to the new weights which causes the (old) 0 normal tag to not price the issue @byteballet

**Comment by byteballet** [comment]
> [ubiquibot/staging#144](https://github.com/ubiquibot/staging/issues/144) tags haven't been changed in accordance to the new weights which causes the (old) 0 normal tag to not price the issue @byteballet

IMO, we are going to shift the priority tag.
https://github.com/ubiquity/ubiquibot/pull/627#discussion_r1297758520

>So in this case we would shift them all up by one, meaning, Priority: 1 (Normal) would be the first value, and we can delete the weight property.

https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228

@Draeieg

**Comment by Draeieg** [comment]
> > [ubiquibot/staging#144](https://github.com/ubiquibot/staging/issues/144) tags haven't been changed in accordance to the new weights which causes the (old) 0 normal tag to not price the issue @byteballet
> 
> I thought, we are going to shift the priority tag. [#627 (comment)](https://github.com/ubiquity/ubiquibot/pull/627#discussion_r1297758520)
> 
> > So in this case we would shift them all up by one, meaning, Priority: 1 (Normal) would be the first value, and we can delete the weight property.
> 
> [#383 (comment)](https://github.com/ubiquity/ubiquibot/pull/383#discussion_r1254078228)
> 
> @Draeieg

@pavlovcik if this is OK then QA is approved

**Comment by pavlovcik** [comment]
> [ubiquibot/staging#144](https://github.com/ubiquibot/staging/issues/144) tags haven't been changed in accordance to the new weights which causes the (old) 0 normal tag to not price the issue @byteballet

Yeah we can update the priority numbers.

**Review by Draeieg — APPROVED** [review]

**Review by whilefoo — APPROVED** [review]
