### PR TITLE
feat: autopay fix

### LINKED ISSUE #290: `/autopay` Command
1. Add a new command `/autopay true|false` that enables/disables permit2 URL payouts for a particular issue.
2. The bot should respond with a success message
3. On issue close and `autopay == false` the bot should display a warning message of why a permit URL is not generated
4. Update help menu accordingly

Notice that there is the `auto-pay-mode` bot's param which enables/disables automatic payments for the whole org/repo. The `/autopay true|false` command should take precedence on the particular issue over the bot's config.

### PR DESCRIPTION
**Pull request by wannacfuture**
Resolves #290 
QA link: https://github.com/wannacfuture/Battleship/issues/71#issuecomment-1665609318

### CODE REVIEW

File: src/handlers/comment/handlers/payout.ts [hunk 1]
```diff
@@ -40,3 +41,26 @@ export const payout = async (body: string) => {
...
+
+  const pattern = /^\/autopay (true|false)$/;
+  const res = body.match(pattern);
+
+  if (res) {
+    const userPermission = await getUserPermission(payload.sender.login, context);
+    if (userPermission !== "admin") {
+      return "Permission required to set autopay mode.";
+    }
+    if (res) {
```
Comment (0xcodercrane) [inline src/handlers/comment/handlers/payout.ts:61]: What does this line do? You are already checking like `if (res)`. Maybe it should be like `if (res.length > 1)`?!?!

File: src/handlers/payout/action.ts [hunk 2]
```diff
@@ -88,6 +89,22 @@ export const handleIssueClosed = async () => {
   }
 
   logger.info(`Handling issues.closed event, issue: ${issue.number}`);
+
+  for (const botComment of comments.filter((cmt) => cmt.user.type === "Bot").reverse()) {
```
Comment (0xcodercrane) [inline src/handlers/payout/action.ts:93]: We have a global variable somewhere for `Bot`, I pretty much don't like using hardcoded values.

**Review by 0xcodercrane — CHANGES_REQUESTED** [review]

File: src/handlers/comment/handlers/payout.ts (hunk 1 above)
Comment (wannacfuture) [reply src/handlers/comment/handlers/payout.ts]: fixed

File: src/handlers/payout/action.ts [hunk 3]
```diff
@@ -100,14 +99,13 @@ export const handleIssueClosed = async () => {
...
         }
-        return;
       }
     }
   }
 
-  if (!autoPayMode) {
-    logger.info(`Skipping to generate permit2 url, reason: { autoPayMode: ${autoPayMode}}`);
-    return `Permit generation skipped since autoPayMode is disabled`;
+  if (paymentPermitMaxPrice == 0) {
```
Comment (pavlovcik) [inline src/handlers/payout/action.ts:106]: Please make sure to handle if this `paymentPermitMaxPrice` is `undefined` in the config? Unless it will automatically default to `0` if it is not defined.

File: src/configs/strings.ts [hunk 4]
```diff
@@ -2,4 +2,5 @@ export const GLOBAL_STRINGS = {
   unassignComment: "Releasing the bounty back to dev pool because the allocated duration already ended!",
   askUpdate: "Do you have any updates",
   assignCommandDisabledComment: "The `/assign` command is disabled for this repository.",
+  autopaycomment: "Autopay mode for this issue is set:",
```
Comment (pavlovcik) [inline src/configs/strings.ts:5]:
```suggestion
  autopaycomment: "Payment permit generation for this issue is enabled:",
```

It would be more elegant to write:
- "Payment permit generation for this issue is enabled."
- "Payment permit generation for this issue is disabled."

File: src/handlers/comment/handlers/index.ts [hunk 5]
```diff
@@ -225,6 +226,12 @@ export const userCommands = (): UserCommands[] => {
     handler: payout,
     callback: commandCallback,
   },*/
+    {
+      id: IssueCommentCommands.AUTOPAY,
+      description: "Disable/enable autopay for a certain issue",
```
Comment (pavlovcik) [inline src/handlers/comment/handlers/index.ts:231]:
```suggestion
      description: "Toggle automatic payment for the current issue.",
```

**Comment by wannacfuture** [comment]
Ready for review. @0xcodercrane

File: src/handlers/comment/handlers/payout.ts [hunk 6]
```diff
@@ -40,3 +41,26 @@ export const payout = async (body: string) => {
...
+  if (res) {
+    const userPermission = await getUserPermission(payload.sender.login, context);
+    if (userPermission !== "admin") {
+      return "Permission required to set autopay mode.";
+    }
+    if (res.length > 1) {
+      return `${GLOBAL_STRINGS.autopaycomment} **${res[1]}**`;
+    }
+  }
+  return "Invalid body for autopay command: e.g. /autopay true|false";
```
Comment (pavlovcik) [inline src/handlers/comment/handlers/payout.ts:65]:
```suggestion
  return "Invalid body for autopay command: e.g. /autopay false";
```

File: src/handlers/payout/action.ts [hunk 7]
```diff
@@ -88,10 +89,26 @@ export const handleIssueClosed = async () => {
...
-  if (paymentPermitMaxPrice == 0) {
+  for (const botComment of comments.filter((cmt) => cmt.user.type === UserType.Bot).reverse()) {
+    const botCommentBody = botComment.body;
+    if (botCommentBody.includes(GLOBAL_STRINGS.autopaycomment)) {
+      const pattern = /\*\*(\w+)\*\*/;
+      const res = botCommentBody.match(pattern);
+      if (res) {
+        if (res[1] === "false") {
+          logger.info(`Skipping to generate permit2 url, reason: autoPayMode for this issue: false`);
+          return `Permit generation skipped since autoPayMode for **THIS ISSUE** is disabled`;
```
Comment (pavlovcik) [inline src/handlers/payout/action.ts:100]:
```suggestion
          return `Permit generation skipped since autoPayMode for ${issue} is disabled`;
```
I'm not sure what the correct variable is but shouldn't it be specific for the log?

Comment (wannacfuture) [reply src/handlers/payout/action.ts:100]: It is the comment for informing that autopay is disabled for a specific issue.
It's not a log.
So, it does more make sense to do that.

File: src/handlers/comment/handlers/payout.ts [hunk 8]
```diff
@@ -40,3 +41,26 @@ export const payout = async (body: string) => {
...
+
+export const autoPay = async (body: string) => {
+  const context = getBotContext();
+  const _payload = context.payload;
+  const logger = getLogger();
+
+  const payload = _payload as Payload;
+  logger.info(`Received '/autopay' command from user: ${payload.sender.login}`);
+
+  const pattern = /^\/autopay (true|false)$/;
```
[the remark this answers is not in the document]
Comment (wannacfuture) [reply src/handlers/comment/handlers/payout.ts:53]: currently only /autopay command uses true | false values.

File: src/handlers/comment/handlers/payout.ts [hunk 9]
```diff
@@ -40,3 +41,26 @@ export const payout = async (body: string) => {
...
+  const res = body.match(pattern);
+
+  if (res) {
+    const userPermission = await getUserPermission(payload.sender.login, context);
+    if (userPermission !== "admin") {
```
[the remark this answers is not in the document]
Comment (wannacfuture) [reply src/handlers/comment/handlers/payout.ts]: added billing_manager role check

**Review by 0xcodercrane — APPROVED** [review]

**Comment by 0xcodercrane** [comment]
@wannacfuture would you resolve conflicts?

**Comment by pavlovcik** [comment]
@0xcodercrane for such simple merge conflicts you should just fix them in the GitHub UI so we can close and merge things faster. Or else we're going to keep this unacceptable amount of pull requests open.

File: src/handlers/payout/action.ts [hunk 10]
```diff
@@ -88,7 +89,22 @@ export const handleIssueClosed = async () => {
...
```
Comment (pavlovcik) [inline src/handlers/payout/action.ts:100]:
```suggestion
          return `Permit generation skipped since automatic payment for this issue is disabled.`;
```

File: src/handlers/comment/handlers/payout.ts [hunk 11]
```diff
@@ -40,3 +41,26 @@ export const payout = async (body: string) => {
...
+  const payload = _payload as Payload;
+  logger.info(`Received '/autopay' command from user: ${payload.sender.login}`);
+
+  const pattern = /^\/autopay (true|false)$/;
+  const res = body.match(pattern);
+
+  if (res) {
+    const userPermission = await getUserPermission(payload.sender.login, context);
+    if (userPermission !== "admin" && userPermission !== "billing_manager") {
+      return "Permission required to set autopay mode.";
```
Comment (pavlovcik) [inline src/handlers/comment/handlers/payout.ts:59]:
```suggestion
      return "You must be an `admin` or `billing_manager` to toggle automatic payments for completed issues.";
```

File: src/configs/strings.ts [hunk 12]
```diff
@@ -2,4 +2,5 @@ export const GLOBAL_STRINGS = {
   unassignComment: "Releasing the bounty back to dev pool because the allocated duration already ended!",
   askUpdate: "Do you have any updates",
   assignCommandDisabledComment: "The `/assign` command is disabled for this repository.",
+  autopaycomment: "Automatic payment for this issue is enabled:",
```
Comment (pavlovcik) [inline src/configs/strings.ts:5]:
```suggestion
  autopayComment: "Automatic payment for this issue is enabled:",
```

Comment (wannacfuture) [reply src/configs/strings.ts]: fixed including related imports.
