### PR TITLE
Error notification

### LINKED ISSUE #800: Logs: Error Notifications
- Depends on https://github.com/ubiquity/ubiquibot-telegram/issues/37
   - Once the webhook is up, we should dump errors there so that we all receive push notifications in a group chat when the bot fails to run.

### PR DESCRIPTION
**Pull request by seprintour**
Resolves #800

Join Group: https://t.me/+jII3pgH54N4wNTI5
Quality Assurance: https://t.me/c/1558587400/556

### CODE REVIEW

File: src/adapters/supabase/helpers/log.ts [hunk 1]
```diff
@@ -169,6 +232,13 @@ export class GitHubLogger implements Logger {
 
   warn(message: string | object, errorPayload?: string | object) {
     this.save(message, LogLevel.WARN, errorPayload);
+    this.sendDataWithJwt(message, errorPayload)
+      .then((response) => {
+        console.log("Log Notification Success:", response);
```
Comment (wannacfuture) [inline src/adapters/supabase/helpers/log.ts]: shouldn't we use logger instead of `console.log` or `console.error`?

Comment (seprintour) [reply src/adapters/supabase/helpers/log.ts]: Oh yea, I'd do so now

**Review by 0x4007 — APPROVED** [review]
i'm quite tired now but the QA looks good and nothing jumps out at me in this code as being wrong. Thanks
