### PR TITLE
fix: query regex

### LINKED ISSUE #590: Invalid syntax for query command
### Describe the background or context

I experimented today with the 'query' command after enabling in my fork always received 

`Invalid syntax for query command` error, see https://github.com/gitcoindev/ubiquibot/pull/3

I was able to run this command only because I analysed the regex in https://github.com/ubiquity/ubiquibot/blob/development/src/handlers/comment/handlers/query.ts

By default GitHub adds an empty space after username after typing @username and this is rejected as the regex does not allow any white space after user name.

### Describe the solution

Proposal to fix this: Update the regex to allow to add an optional empty white space after user name.

### PR DESCRIPTION
**Pull request by EtherealGlow**
Resolves #590

### CODE REVIEW

**Comment by EtherealGlow** [comment]
i tested this using a ts debugger but i cannot qa this unfortunately  as i am getting a module not found error and idk why

**Comment by EtherealGlow** [comment]
here is the result from the [debugger](https://regex101.com/r/tajdDM/3)

File: src/handlers/comment/handlers/query.ts [hunk 1]
```diff
@@ -19,7 +19,7 @@ export const query = async (body: string) => {
     return `Skipping '/query' because of no issue instance`;
   }
 
-  const regex = /^\/query\s@(\w+)$/;
+  const regex = /(?<=\/query @)\w+/g
```
Comment (whilefoo) [inline src/handlers/comment/handlers/query.ts:22]: this regex is different than your debugger and the positive lookbehind seems rather unnecessary, this can be done with simple capturing groups.

also please make sure it still matches if you put multiple spaces between like `/query    @test`

File: src/handlers/comment/handlers/query.ts [hunk 2]
```diff
@@ -19,7 +19,7 @@ export const query = async (body: string) => {
...
   const matches = body.match(regex);
```
Comment (whilefoo) [inline src/handlers/comment/handlers/query.ts:23]: `match` function behaves [differently](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/match#return_value) when a regex is global like yours `/g`. I think we don't need global regex because we are just searching for one instance of query

**Review by whilefoo — CHANGES_REQUESTED** [review]

File: src/handlers/comment/handlers/query.ts [hunk 3]
```diff
@@ -19,9 +19,9 @@ export const query = async (body: string) => {
     return `Skipping '/query' because of no issue instance`;
   }
 
-  const regex = /^\/query\s@(\w+)$/;
+  const regex = /^\/query\s+(@\w+)\s?$/;
```
Comment (whilefoo) [inline src/handlers/comment/handlers/query.ts:22]:
```suggestion
  const regex = /^\/query\s+@([\w-]+)\s*$/;
```

if you put `@` out of the capture group you don't need substring, username can contain `-` and we can allow for zero or multiple whitespace chars at the end

File: src/handlers/comment/handlers/query.ts [hunk 4]
```diff
@@ -19,9 +19,9 @@ export const query = async (body: string) => {
...
   const matches = body.match(regex);
-  const user = matches?.[1];
+  const user = matches?.[1].substring(1);
```
Comment (whilefoo) [inline src/handlers/comment/handlers/query.ts:24]:
```suggestion
  const user = matches?.[1];
```

**Review by whilefoo — CHANGES_REQUESTED** [review]

**Review by web4er — CHANGES_REQUESTED** [review]
> i tested this using a ts regex debugger but i cannot qa this unfortunately as i am getting a module not found error and idk why

This should have a QA. Maybe try the following if you haven't already. 
```sh
yarn clean
yarn 
yarn build 
yarn start
```

**Comment by EtherealGlow** [comment]
@web4er it is finding the user now but i cant set the address

**Comment by EtherealGlow** [comment]
[qa](https://github.com/EtherealGlow/ubiquibot/issues/10)

File: src/handlers/comment/handlers/query.ts (hunk 3 above)
Comment (pavlovcik) [reply src/handlers/comment/handlers/query.ts]: We can simplify everything by just taking the comment corpus and trimming it `String.trim();` when it enters this function?

**Review by whilefoo — APPROVED** [review]

**Comment by pavlovcik** [comment]
@web4er just needs your approval for merge

**Review by web4er — APPROVED** [review]
> @web4er just needs your approval for merge

QA: https://github.com/web4erOrg/ubiquibot/issues/32

Working ok.
